spring:
  datasource:
    url: jdbc:sqlite:map.sqlite # 创建的sqlite数据库所在路径
    username: # 因为没有用户名和密码，所以这两个参数就没有值
    password:
    driver-class-name: org.sqlite.JDBC # sqlite驱动

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置mapper.xml文件路径
  type-aliases-package: pro.niunai.bilibili.record.map.pojo # 实体类包名
  configuration:
    map-underscore-to-camel-case: true
# mybatis 打印SQL, 配置后就会在控制台打印执行的SQL语句
logging:
  level:
    pro.niunai.bilibili.record.map: trace

knife4j:
  # 开启增强配置
  enable: true
  # 生产环境屏蔽，开启将禁止访问在线API文档
  production: false
  # Basic认证功能，即是否需要通过用户名、密码验证后才可以访问在线API文档
  basic:
    # 是否开启Basic认证
    enable: false
    # 用户名，如果开启Basic认证却未配置用户名与密码，默认是：admin/123321
    username: root
    # 密码
    password: root
